[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_buy_program = "Hktf94z7aAKJkTaBmaRLe5WZyLsWXQws3TvCkwCEsEbp"

[registry]
url = " https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
